import re
from langchain_openai import ChatOpenAI
from langchain.prompts import ChatPromptTemplate
from langchain.chains import LLMChain
from utils import invoke_agent_with_retry
from proposers import parse_proposals_markdown # Import parser from proposers

# Summarizer Agent Prompt Template (kept here)
summarizer_template_str = """
**You are an AAOIFI Proposal Summarizer.** Your task is to review the proposed enhancements provided below. For each distinct proposed enhancement, create a concise summary entry containing *only* the Proposal Title and a brief description of the proposed change.

**Standard Name:** '{standard_name}' ('{standard_short_name}')

**Input: Proposed Enhancements from Proposers (Simplified Markdown):**
---
{all_proposals_simplified_markdown}
---

**Instructions:**
Review the provided list of proposals (Title and Description only). Identify each unique proposal. For each unique proposal, create a concise summary entry.

**Output Format:**
Provide a list of proposal summaries using markdown.

---
## Summarized Proposals for '{standard_name}'
*   **[Proposal Title 1]:** [Concise Description of Proposed Change 1]
*   **[Proposal Title 2]:** [Concise Description of Proposed Change 2]
*   ... (Continue for all unique proposals found in the input)
---
"""
summarizer_prompt = ChatPromptTemplate.from_template(summarizer_template_str)


def run_summarizer_agent(llm_structured: ChatOpenAI, standard_name: str, standard_short_name: str, raw_proposer_outputs_by_persona: dict, max_retries: int, initial_retry_delay: float, RateLimitError):
    """Initializes and runs the Summarizer agent."""
    summarizer_chain = LLMChain(llm=llm_structured, prompt=summarizer_prompt)
    print("\n--- Step 3: Running Summarizer Agent ---")

    # --- Create a lighter, combined input for the Summarizer from parsed proposals ---
    all_proposals_simplified_markdown = ""
    temp_all_proposals = [] # Parse raw outputs first to get titles/descriptions

    # Collect all parsed proposals from raw outputs
    for persona_key, proposer_output in raw_proposer_outputs_by_persona.items():
        parsed_proposals = parse_proposals_markdown(proposer_output) # Use imported parser
        temp_all_proposals.extend(parsed_proposals)

    # Build simplified markdown from the collected parsed proposals
    if temp_all_proposals:
        # Use a dictionary to track unique titles to avoid duplication in simplified list
        unique_proposals_for_summarizer = {}
        for prop in temp_all_proposals:
             title = prop.get("title", "Untitled").strip()
             # Clean title potential markdown artifacts
             title = re.sub(r'^\s*Proposed Enhancement:\s*', '', title, flags=re.IGNORECASE).strip() # Remove potential prefix
             title = re.sub(r'\*\*:?$', '', title).strip()
             # Ensure title is not empty after cleaning before considering it unique
             if title and title not in unique_proposals_for_summarizer:
                 unique_proposals_for_summarizer[title] = prop # Store the first occurrence

        if unique_proposals_for_summarizer:
            all_proposals_simplified_markdown += "## Proposed Enhancements Summary for LLM\n\n" # Add a clear header
            for title, prop in unique_proposals_for_summarizer.items():
                description = prop.get("description", "No description provided.").strip()
                all_proposals_simplified_markdown += f"*   **{title}:** {description}\n"
        else:
             all_proposals_simplified_markdown = "No distinct proposals were identified."

    # --- DEBUG PRINT ---
    # print("\n--- Debug: Simplified Markdown for Summarizer ---")
    # print(all_proposals_simplified_markdown)
    # print("--------------------------------------------")
    # --- END DEBUG PRINT ---


    # If no proposals were parsed/simplified, handle that case
    if not all_proposals_simplified_markdown.strip() or all_proposals_simplified_markdown == "No distinct proposals were identified.":
         print("Skipping summarizer as no significant proposals were generated or parsed.")
         all_proposals_summarized_markdown = "No proposals were generated by any agent."
    else:
         inputs = {
             "standard_name": standard_name,
             "standard_short_name": standard_short_name,
             "all_proposals_simplified_markdown": all_proposals_simplified_markdown # Pass the simplified markdown
         }
         summarizer_result = invoke_agent_with_retry(summarizer_chain, inputs, max_retries, initial_retry_delay, RateLimitError)
         all_proposals_summarized_markdown = summarizer_result['text'].strip()

    print("\nSummarizer Output:")
    print(all_proposals_summarized_markdown)
    return all_proposals_summarized_markdown